# ---------------------------------------------------------------------- #
#           NOTE: ALL SAMPLE DATA WAS GENERATED FROM CHATGPT             #
# BY PROVIDING CATEGORIES LISTED IN THE READ-ME AND HAVING IT GENERATE   #
# COMPANIES THAT ARE ASSOCIATED WITH PARENT CATEGORIES                   #
# EXPENSES WERE GENERATED BY GIVING IT ALL USERS/VENDORS AND SUB CATEGORY#
# ASIDE FROM THOSE SCENARIOS EVERYTHING ELSE WAS CODED BY MYSELF         #
# ---------------------------------------------------------------------- #

DROP DATABASE IF EXISTS financial;
CREATE DATABASE IF NOT EXISTS financial;
USE financial;

# ---------------------------------------------------------------------- #
# CREATE TABLES                                                          #
# ---------------------------------------------------------------------- #

CREATE TABLE users
(
	user_id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) GENERATED ALWAYS AS (CONCAT(first_name, " ", last_name)) STORED,
    PRIMARY KEY (user_id)
);

CREATE TABLE vendors 
(
	vendor_id INT NOT NULL AUTO_INCREMENT,
    vendor_name VARCHAR(50) NOT NULL,
    PRIMARY KEY(vendor_id)
);

CREATE TABLE categories
(
	category_id INT NOT NULL AUTO_INCREMENT,
    category_name VARCHAR(50) NOT NULL,
    PRIMARY KEY(category_id)
);

CREATE TABLE sub_categories
(
	sub_category_id INT NOT NULL AUTO_INCREMENT,
    sub_category_name VARCHAR(50) NOT NULL,
    parent_id INT NOT NULL,
    PRIMARY KEY(sub_category_id),
    FOREIGN KEY(parent_id) REFERENCES categories(category_id)
);

CREATE TABLE expenses
(	
	expense_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    vendor_id INT NOT NULL,
    category_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    date DATE NOT NULL,
    note TINYTEXT,
    PRIMARY KEY (expense_id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id),
    FOREIGN KEY (category_id) REFERENCES sub_categories(sub_category_id)
);
# ---------------------------------------------------------------------- #
# INSERT USERS DATA                                                      #
# ---------------------------------------------------------------------- #
INSERT users (first_name, last_name) VALUES
('Sarah', 'Smith'),
('John', 'Doe');
# ---------------------------------------------------------------------- #
# INSERT VENDORS DATA                                                    #
# ---------------------------------------------------------------------- #
INSERT INTO vendors (vendor_name) VALUES
('TechGuru Electronics'),
('HomeEssentials Housing'),
('FunTimes Entertainment'),
('TravelMate Vacations'),
('GourmetDelight Food'),
('HealthPlus Healthcare'),
('SmartHome Appliances'),
('AdventureTravel Vacations'),
('FreshEats Groceries'),
('WellnessCare Health');
# ---------------------------------------------------------------------- #
# INSERT PARENT CATEGORIES DATA --- 6                                    #
# ---------------------------------------------------------------------- #
INSERT INTO categories (category_name) VALUES
('Entertainment'),
('Food'),
('Healthcare'),
('Housing'),
('Transportation'),
('Vacation/Travel');
# ---------------------------------------------------------------------- #
# INSERT SUB CATEGORIES DATA --- 5 x 6                                   #
# ---------------------------------------------------------------------- #
INSERT INTO sub_categories (sub_category_name, parent_id) VALUES
-- Entertainment
('Movies', 1),
('Music', 1),
('Theater', 1),
('Video Games', 1),
('Concerts', 1),

-- Food
('Restaurants', 2),
('Cafes', 2),
('Fast Food', 2),
('Bakeries', 2),
('Food Trucks', 2),

-- Healthcare
('Hospitals', 3),
('Clinics', 3),
('Pharmacies', 3),
('Dental Care', 3),
('Optical Care', 3),

-- Housing
('Rentals', 4),
('Real Estate', 4),
('Property Management', 4),
('Home Improvement', 4),
('Storage Solutions', 4),

-- Transportation
('Public Transit', 5),
('Car Rentals', 5),
('Ride-Sharing', 5),
('Taxi Services', 5),
('Bicycles', 5),

-- Vacation/Travel
('Beach Resorts', 6),
('Mountain Retreats', 6),
('City Tours', 6),
('Cruises', 6),
('Adventure Trips', 6);
# ---------------------------------------------------------------------- #
# INSERT EXPENSES DATA                                                   #
# ---------------------------------------------------------------------- #
INSERT INTO expenses (user_id, vendor_id, category_id, amount, date, note) VALUES
-- SARAH SMITH
(1, 1, 2, 60.00, '2024-08-01', 'Bought new gaming console'),
(1, 2, 5, 850.00, '2024-08-02', 'Rent payment for August'),
(1, 3, 8, 55.00, '2024-08-03', 'Eye check-up'),
(1, 4, 10, 150.00, '2024-08-04', 'Dinner at a new cafe'),
(1, 5, 12, 80.00, '2024-08-05', 'Weekly groceries'),
(1, 6, 13, 300.00, '2024-08-06', 'Medical consultation'),
(1, 7, 16, 220.00, '2024-08-07', 'Furniture for home office'),
(1, 8, 19, 2500.00, '2024-08-08', 'Vacation at a mountain retreat'),
(1, 9, 22, 100.00, '2024-08-09', 'Ride-sharing for a business trip'),
(1, 10, 24, 200.00, '2024-08-10', 'Fitness classes subscription'),
(1, 1, 3, 75.00, '2024-08-11', 'Tickets to a theater play'),
(1, 2, 6, 300.00, '2024-08-12', 'Rent payment for August'),
(1, 3, 7, 60.00, '2024-08-13', 'Dental visit'),
(1, 4, 10, 100.00, '2024-08-14', 'Dinner at a new restaurant'),
(1, 5, 12, 70.00, '2024-08-15', 'Grocery shopping'),
(1, 6, 13, 320.00, '2024-08-16', 'Monthly health insurance'),
(1, 7, 16, 180.00, '2024-08-17', 'Home decor purchase'),
(1, 8, 19, 2000.00, '2024-08-18', 'Vacation at a city tour'),
(1, 9, 22, 90.00, '2024-08-19', 'Ride-sharing expenses'),
(1, 10, 24, 180.00, '2024-08-20', 'Fitness membership renewal'),
(1, 1, 3, 85.00, '2024-08-21', 'Theater show tickets'),
(1, 2, 6, 1250.00, '2024-08-22', 'Rent payment for August'),
(1, 3, 11, 100.00, '2024-08-23', 'Optical care appointment'),
(1, 4, 14, 275.00, '2024-08-24', 'Home repair supplies'),
(1, 5, 17, 150.00, '2024-08-25', 'Bike accessories'),
(1, 6, 13, 200.00, '2024-08-26', 'Medical consultation follow-up'),
(1, 7, 16, 160.00, '2024-08-27', 'Home office equipment'),
(1, 8, 15, 1500.00, '2024-08-28', 'Vacation at a city tour'),
(1, 9, 22, 110.00, '2024-08-29', 'Airport shuttle service'),
(1, 10, 24, 190.00, '2024-08-30', 'Extended gym membership'),
(1, 1, 3, 80.00, '2024-09-01', 'Concert tickets'),
(1, 2, 6, 310.00, '2024-09-02', 'Rent payment for September'),
(1, 3, 7, 65.00, '2024-09-03', 'Dental visit'),
(1, 4, 10, 120.00, '2024-09-04', 'Dinner at a fancy restaurant'),
(1, 5, 12, 85.00, '2024-09-05', 'Grocery shopping'),
(1, 6, 13, 330.00, '2024-09-06', 'Medical consultation'),
(1, 7, 16, 190.00, '2024-09-07', 'Home decor purchase'),
(1, 8, 19, 2100.00, '2024-09-08', 'Vacation at a beach resort'),
(1, 9, 22, 95.00, '2024-09-09', 'Ride-sharing expenses'),
(1, 10, 24, 170.00, '2024-09-10', 'Fitness membership renewal'),
-- JOHN DOE
(2, 1, 2, 100.00, '2024-08-01', 'Bought a new phone'),
(2, 2, 4, 1300.00, '2024-08-02', 'Rent payment for August'),
(2, 3, 5, 40.00, '2024-08-03', 'Music concert'),
(2, 4, 8, 150.00, '2024-08-04', 'Dinner at a fancy restaurant'),
(2, 5, 9, 80.00, '2024-08-05', 'Weekly grocery shopping'),
(2, 6, 12, 200.00, '2024-08-06', 'Health check-up'),
(2, 7, 13, 350.00, '2024-08-07', 'Home repair services'),
(2, 8, 15, 1500.00, '2024-08-08', 'Vacation at an adventure trip'),
(2, 9, 18, 75.00, '2024-08-09', 'Taxi service for airport'),
(2, 10, 20, 120.00, '2024-08-10', 'Gym membership renewal'),
(2, 1, 1, 55.00, '2024-08-11', 'New gaming accessories'),
(2, 2, 5, 1200.00, '2024-08-12', 'Rent payment for August'),
(2, 3, 7, 60.00, '2024-08-13', 'Dental visit'),
(2, 4, 10, 100.00, '2024-08-14', 'Dinner at a new restaurant'),
(2, 5, 12, 70.00, '2024-08-15', 'Grocery shopping'),
(2, 6, 13, 320.00, '2024-08-16', 'Monthly health insurance'),
(2, 7, 16, 180.00, '2024-08-17', 'Home decor purchase'),
(2, 8, 19, 2000.00, '2024-08-18', 'Vacation at a city tour'),
(2, 9, 22, 90.00, '2024-08-19', 'Ride-sharing expenses'),
(2, 10, 24, 180.00, '2024-08-20', 'Fitness membership renewal'),
(2, 1, 3, 85.00, '2024-08-21', 'Theater show tickets'),
(2, 2, 6, 1250.00, '2024-08-22', 'Rent payment for August'),
(2, 3, 11, 100.00, '2024-08-23', 'Optical care appointment'),
(2, 4, 14, 275.00, '2024-08-24', 'Home repair supplies'),
(2, 5, 17, 150.00, '2024-08-25', 'Bike accessories'),
(2, 6, 13, 200.00, '2024-08-26', 'Medical consultation follow-up'),
(2, 7, 16, 160.00, '2024-08-27', 'Home office equipment'),
(2, 8, 15, 1500.00, '2024-08-28', 'Vacation at a city tour'),
(2, 9, 22, 110.00, '2024-08-29', 'Airport shuttle service'),
(2, 10, 24, 190.00, '2024-08-30', 'Extended gym membership'),
(2, 1, 3, 80.00, '2024-09-01', 'Concert tickets'),
(2, 2, 6, 310.00, '2024-09-02', 'Rent payment for September'),
(2, 3, 7, 65.00, '2024-09-03', 'Dental visit'),
(2, 4, 10, 120.00, '2024-09-04', 'Dinner at a fancy restaurant'),
(2, 5, 12, 85.00, '2024-09-05', 'Grocery shopping'),
(2, 6, 13, 330.00, '2024-09-06', 'Medical consultation'),
(2, 7, 16, 190.00, '2024-09-07', 'Home decor purchase'),
(2, 8, 19, 2100.00, '2024-09-08', 'Vacation at a beach resort'),
(2, 9, 22, 95.00, '2024-09-09', 'Ride-sharing expenses'),
(2, 10, 24, 170.00, '2024-09-10', 'Fitness membership renewal');
